#spring:
#  kafka:
#    bootstrap-servers: 10.5.2.194:9092,10.5.2.194:9093
#    enable-auto-commit: false
#    auto-commit-interval-ms: 100
#    session-timeout-ms: 15000
#    group-id: migu-group
#    auto-offset-reset: latest
#    retries: 2
#    batch-size: 4096
#    linger-ms: 1
#    buffer-memory: 40960
#  redis:
#    database: 0
#    host: 10.5.2.194
#    password: 
#    port: 6379
#    timeout: 300
#    pool:
#      max-idle: 8
#      min-idle: 0
#      max-active: 500
#      max-wait: 100000
#    cluster:
#      nodes: 10.5.2.194:7000,10.5.2.194:7001,10.5.2.194:7002,10.5.2.194:7003,10.5.2.194:7004,10.5.2.194:7005
#      password: null
#      timeout: 300
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 500
#        max-wait: 100000
#    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.5.2.194:10003/eureka/
#  instance:
#    prefer-ip-address: true


## 数据库配置
spring:
  datasource:
    url: jdbc:mysql://10.5.2.194:3306/product_center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: productdev
    password: productdev
