#spring:
#  kafka:
#    bootstrap-servers: 10.5.2.194:9092,10.5.2.194:9093
#    enable-auto-commit: false
#    auto-commit-interval-ms: 100
#    session-timeout-ms: 15000
#    group-id: migu-group
#    auto-offset-reset: latest
#    retries: 2
#    batch-size: 4096
#    linger-ms: 1
#    buffer-memory: 40960
#  redis:
#    database: 0
#    host: 10.5.2.194
#    password: 
#    port: 6379
#    timeout: 300
#    pool:
#      max-idle: 8
#      min-idle: 0
#      max-active: 500
#      max-wait: 100000
#    cluster:
#      nodes: 10.5.2.194:7000,10.5.2.194:7001,10.5.2.194:7002,10.5.2.194:7003,10.5.2.194:7004,10.5.2.194:7005
#      password: null
#      timeout: 300
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 500
#        max-wait: 100000
#    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.5.2.194:10003/eureka/
#  instance:
#    prefer-ip-address: true


## 数据库配置
#spring:
#  datasource:
#    url: jdbc:mysql://10.5.2.243:3306/product_center_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: producttest
#    password: producttest
#    driverClassName: com.mysql.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://10.5.2.194:3306/product_center_dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: productdev
    password: productdev
    driverClassName: com.mysql.jdbc.Driver
#连接池的配置信息
## 初始化大小，最小，最大
#  druid:
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#### 配置获取连接等待超时的时间    
#    maxWait: 60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒    
#    timeBetweenEvictionRunsMillis: 60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙    
#    filters: stat,wall,log4j
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#mybatis
#mybatis:
#  type-aliases-package: com.example.demo.mapper
#  mapper-locations: classpath:com/example/demo/mapper/*.xml

myconfig:
  name: yzx-dev
  tech: Docker


